[project]
name = "selectivity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cvxopt>=1.3.2",
    "gurobipy>=12.0.2",
    "numpy>=2.0.2",
    "pip>=25.1.1",
    "scipy>=1.13.1",
]
